# Fallstudie Gesundheitsevalution (HELP-Studie) {#HELPstudie}

Viele Beispiele in diesem Buch greifen auf Daten der \textsc{HELP}-Studie zurück. Bei dieser Studie handelt es sich um eine randomisierte klinische Studie mit Patienten, aus einer stationären Drogenentzugsanstalt. Patienten ohne laufende allgemeinmedizinische Versorgung wurden randomisiert entweder in einer Gruppe, in der sie eine multidisziplinäre Untersuchung und eine kurze Motivationsintervention erhielten, oder einer Gruppe mit Standardbehandlung zugeteilt. Ziel war diese Patienten an die medizinische Grundversorgung anzubinden.^[Die \textsc{HELP}-Studie wurde finanziert durch das *National Institute on Alcohol Abuse and Alcoholism* (R01-AA10870, Samet PI) sowie das *National Institute on Drug Abuse* (R01-DA10019, Samet PI).] Die Ergebnisse der Studie wurden zusammen mit einer Reihe von zusätzlichen Analysen veröffentlicht [@samet2003; @liebschutz2002; @kertesz2003].

Teilnehmer an der Studie mussten erwachsen sein, Spanisch oder Englisch sprechen und Alkohol, Heroin oder Kokain als ihre Hauptdroge angeben. Außerdem mussten sie in der Nähe in der Klinik wohnen, in der sie behandelt werden sollten, oder obdachlos sein. Ausschlusskriterien waren: a) laufende Versorgung und Absicht, diese weiterzuführen, b) fortgeschrittene Demenz, c) konkrete Pläne, die Gegend um Boston zu verlassen, so dass sie nicht an einer Behandlung teilnehmen konnten, d) keine Angabe von Kontaktinformationen oder e) Schwangerschaft.

Die Teilnehmer wurden zu Beginn ihres Entzugsaufenthaltes befragt sowie alle sechs Monate für die Dauer von zwei Jahren erneut befragt. Dabei wurde eine Anzahl von metrisch-, ordinal- und nominal-skalierten sowie Daten für Überlebenszeitanalysen^[Survival Time Analysis] zu jedem der fünf Zeitpunkte erhoben. Die Ethikkommission des  Medizinischen Zentrums der Universität Boston überprüfte das Studienkonzept, insbesondere die Erstellung eines anonymisierten Datensatzes. Das Zertifikat für Datenschutz, ausgestellt durch das *Department of Health and Human Services*, bescheinigt weitere Datenschutzmaßnahmen. 

Das \textsf{R}-Paket `mosaicData` enthält mehrere Varianten des anonymisierten  \textsc{HELP}-Datensatzes. Für die vorliegende Fallstudie konzentrieren wir uns auf den `HELPrct`-Datensatz, der 27 Variablen zu 453 Personen enthält, wobei vergleichsweise wenig Daten fehlen, besonders zum ersten Messzeitpunkt. Tabelle \@ref(tab:tabhelp). Weitere Informationen finden sich online unter [http://www.amherst.edu/~nhorton/r2](http://www.amherst.edu/~nhorton/r2). Die Messinstrumente sind hier aufgeführt: [http://www.amherst.edu/~nhorton/help](http://www.amherst.edu/~nhorton/help).

\newpage
\thispagestyle{empty}
```{r tabhelp, echo=FALSE}
HELPdat <- read.csv("data/help.csv")
HELPdat <- HELPdat[, 1:3]

knitr::kable(HELPdat[-26, ], booktabs = TRUE, 
             col.names = c("Variable", "Beschreibung", "Hinweis"),
             caption = "Variablen des Datensatzes zur HELP-Studie") %>% 
  landscape(margin = "1.5cm") %>%
  kable_styling(latex_options = "scale_down") %>% 
  footnote(general = HELPdat[26,3])
```
