--- 
title: "Mosaic-Handbuch"
subtitle: "Übersetzung des englischen Originals"
author: "FOM"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
version: "v0.0.1"
site: bookdown::bookdown_site
documentclass: scrbook
bibliography: [bib/book.bib, bib/packages.bib, bib/article.bib]
link-citations: yes
description: "Dies ist die Übersetzung des 'Student's Guide to R' von Daniel T. Kaplan, Nicholas J. Horton und Randall Pruim aus dem Project Mosaic."

lang: de-DE
colorlinks: yes
geometry: "left=3cm,right=3cm,top=2cm,bottom=2cm"
---

```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(mosaic)
library(kableExtra)
```

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', prompt=TRUE, out.width="60%", fig.align='center', warning=FALSE, message=FALSE
)
```

```{r data, echo=FALSE}
data(HELPrct)
data(iris)
data(faithful)
```



# Vorwort {-}

Das ist das (noch zu schreibende) Vorwort für die deutsche Version des mosaic-Handbuchs.


Dieses Buch baut technnisch auf *knitr* [@xie2015], *rmarkdown* [@R-rmarkdown], R [@R-base] und vielen weiteren Open-Source-Anwendungen. Details sind im Kapitel \@ref(hinweise) hinterlegt. Lorem Ipsum.